# The following variables are expected to be set:
# DO_DEPLOY: Whether or not to deploy.
# NO_BUILD_NUMBER: Whether to include the build number in the artifacts' version numbers.
# SIGNING_KEY: The key to use for signing artifacts.
# SIGNING_PASSWORD: The password for the signing key.
# DEPLOY_REPO_URL: URL of the repository to deploy artifacts to.
# DEPLOY_REPO_USERNAME: User name for logging in with the repository.
# DEPLOY_REPO_PASSWORD: Password for logging in with the repository.
image: adoptopenjdk:13-jdk-hotspot

include:
  - template: Code-Quality.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  # Put GRADLE_USER_HOME into the cache directory so the wrapper is not
  # re-downloaded for every job.
  - export GRADLE_USER_HOME=/cache/.gradle

cache:
  key: ${CI_COMMIT_REF_SLUG}

stages:
  - build
  - test

build:
  stage: build
  tags:
    - opentcs-runner
  script:
    - echo "CI_PIPELINE_IID is $CI_PIPELINE_IID"
    - echo "DO_DEPLOY is $DO_DEPLOY"
    - echo "NO_BUILD_NUMBER is $NO_BUILD_NUMBER"
    - echo "DEPLOY_REPO_URL is $DEPLOY_REPO_URL"
    - echo "DEPLOY_REPO_USERNAME is $DEPLOY_REPO_USERNAME"
    - 'if [ "$DO_DEPLOY" = "true" ]; then
        echo "Executing build with deployment...";
        ./gradlew clean build publish -PNO_BUILD_NUMBER="$NO_BUILD_NUMBER" -PSIGNING_KEY="$SIGNING_KEY" -PSIGNING_PASSWORD="$SIGNING_PASSWORD" -PDEPLOY_REPO_URL="$DEPLOY_REPO_URL" -PDEPLOY_REPO_USERNAME="$DEPLOY_REPO_USERNAME" -PDEPLOY_REPO_PASSWORD="$DEPLOY_REPO_PASSWORD";
      else
        echo "Executing build without deployment...";
        ./gradlew clean build -PNO_BUILD_NUMBER="$NO_BUILD_NUMBER";
      fi'
  artifacts:
    paths:
      - build/distributions/*.zip
    reports:
      junit: openTCS-*/build/test-results/test/TEST-*.xml
    when: always

code_quality:
  stage: test
  tags:
    - opentcs-runner
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the master branch (but not in other branch pipelines)
    - if: '$CI_COMMIT_TAG'                               # Run code quality job in pipelines for tags
